LastPet/petweb/pet/meowoof/urls.py
from django.urls import path

from . import views

app_name = 'meowoof'  # 使用名字空间

urlpatterns = [

    # 首页
    path('index/', views.index, name='index'),

    # 宠物图鉴详情页面
    path('pet_detail/<int:pet_id>/', views.pet_detail, name='pet_detail'),
    # 宠物用品详情界面
    path('tool_detail/<int:tool_id>/', views.tool_detail, name='tool_detail'),
    # 登录页面
    path('login/', views.login, name='login'),

    # 注册页面
    path('register/', views.register, name='register'),

    # 退出登录
    path('logout/', views.logout, name='logout'),

    # 展示界面
    path('pet/', views.pet, name='pet'),
    path('tool/', views.tool, name='tool'),
    path('suggestion/', views.suggestion, name='suggestion'),


    # 用户个人主页
    path('myself/', views.myself, name='myself'),
    path('myself_pet_collect/', views.myself_pet_collect, name='myself_pet_collect'),
    path('myself_tool_collect/', views.myself_tool_collect, name='myself_tool_collect'),
    # 更改个人信息
    path('modify_myself/', views.modify_myself, name='modify_myself'),

    # 处理用户点赞,收藏
    path('like_comment/<int:comment_id>/', views.like_comment, name='like_comment'),
    path('collect_pet/<int:pet_id>/', views.collect_pet, name='collect_meal'),
    path('collect_tool/<int:tool_id>/', views.collect_tool, name='collect_meal'),

    # 搜索结果界面
    path('pet_search_result/', views.pet_search_result, name='pet_search_result'),
    path('tool_search_result/', views.tool_search_result, name='tool_search_result'),
]

LastPet/petweb/pet/pet/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('meowoof/', include('meowoof.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LastPet/petweb/pet/meowoof/models.py
from django.db import models

# Create your models here.

# 用户类
# duhao sjtusjtu 超级管理员的账号和密码
class User(models.Model):
    user_name = models.CharField(max_length=20, unique=True, verbose_name='用户名', blank=False, null=False)
    password = models.CharField(max_length=200, verbose_name='密码', null=False, blank=False)
    avatar = models.ImageField(upload_to='user_avatar/', verbose_name='头像', blank=True, null=True,
                               default='user_avatar/default0.jpg')
    telephone = models.CharField(max_length=11, null=True, verbose_name='电话号', blank=True)
    email = models.EmailField(blank=True, null=True, verbose_name='邮箱')
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.user_name

    class Meta:
        ordering = ['-create_time']  # 按时间递减排序
        verbose_name = "用户"
        verbose_name_plural = "用户"



class Pet(models.Model):
    name = models.CharField(max_length=30)  # 宠物名
    picture = models.ImageField(upload_to='pet_picture/', default='default_pet_picture.jpg')  # 宠物图片
    origin = models.CharField(max_length=30) # 宠物发源地
    character = models.CharField(max_length=30) # 宠物性格
    size = models.CharField(max_length=30) # 宠物体型
    info = models.CharField(max_length=2000) # 宠物详细信息

    views = models.IntegerField(default=0, verbose_name='浏览量')

    def __str__(self):  # 返回对象时显示字符串
        return self.name

    class Meta:
        ordering = ['-views']  # 按点赞数递减排序
        verbose_name = "宠物"
        verbose_name_plural = "宠物"

class Tool(models.Model):
    name = models.CharField(max_length=30)  # 宠物用品名
    picture = models.ImageField(upload_to='tool_picture/', default='default_tool_picture.jpg')  # 图片

    info = models.CharField(max_length=2000) # 宠物用品详细信息

    views = models.IntegerField(default=0, verbose_name='浏览量')

    def __str__(self):  # 返回对象时显示字符串
        return self.name

    class Meta:
        ordering = ['-views']  # 按点赞数递减排序
        verbose_name = "用品"
        verbose_name_plural = "用品"



# 这是评论类
class Comment(models.Model):
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE)  # 每一条评论所归属的宠物用品名

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=2000)  # 评论内容
    pub_date = models.DateField(auto_now_add=True)  # 发布日期,自动保存评论的创建日期
    pub_time = models.TimeField(auto_now_add=True)  # 发布时间，自动保存评论的创建时间
    likes = models.IntegerField(default=0)  # 评论点赞数

    def __str__(self):
        return '%s Comment:%s' % (self.tool.name, self.content)

    class Meta:
        ordering = ['-pub_date', '-pub_time']  # 按时间递减排序
        verbose_name = "评论"
        verbose_name_plural = "评论"

class Suggestion(models.Model):
    name = models.CharField(max_length=30)  # 建议标题

    info = models.CharField(max_length=2000) #建议内容

    picture = models.ImageField(upload_to='tool_picture/', default='default_tool_picture.jpg')

    views = models.IntegerField(default=0, verbose_name='浏览量')

    def __str__(self):  # 返回对象时显示字符串
        return self.name

    class Meta:
        ordering = ['-views']  # 按点赞数递减排序
        verbose_name = "建议"
        verbose_name_plural = "建议"

class CollectPet(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '%s收藏了宠物%s' % (self.user.user_name, self.pet.name)

class CollectTool(models.Model):
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '%s收藏了宠物用品%s' % (self.user.user_name, self.tool.name)

LastPet/petweb/pet/meowoof/forms.py
from django import forms
from meowoof.models import Comment, User


# 用户登录表单
class UserLoginForm(forms.Form):
    user_name = forms.CharField(label="用户名", max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Username", 'autofocus': ''}))
    password = forms.CharField(label="密码", max_length=256,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': "Password"}))


# 注册账户表单
class RegisterForm(forms.Form):
    user_name = forms.CharField(label="用户名", max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Username", 'autofocus': ''}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))


# 用户搜索表单
class SearchForm(forms.Form):
    search_text = forms.CharField(label="搜索", max_length=30, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': '请输入搜索内容'}
    ))


# 用户评论表单
class CommentForm(forms.Form):
    class Meta:
        model = Comment
        fields = ['content']


# 修改个人信息表单
class ModifyMyselfForm(forms.Form):
    avatar = forms.ImageField()
    user_name = forms.CharField(label="用户名", max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Username", 'autofocus': ''}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    telephone = forms.CharField(label="电话号码", max_length=128, widget=forms.TextInput(
                attrs={'class': 'form-control'}))

LastPet/petweb/pet/meowoof/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from meowoof.models import *
from django.urls import reverse
from meowoof.forms import *

# 登录页面，已完成
def login(request):
    if request.session.get('is_login', None):  # 不允许重复登录
        return redirect('/meowoof/index/')
    if request.method == 'POST':
        login_form = UserLoginForm(request.POST)
        message = '亲，好像内容不太对哦~'
        if login_form.is_valid():
            username = login_form.cleaned_data.get('user_name')
            password = login_form.cleaned_data.get('password')
            try:
                user = User.objects.get(user_name=username)
            except:
                message = '亲，小生没有查到您的账户哦(⊙o⊙)'
                return render(request, 'meowoof/login.html', locals())

            if user.password == password:
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.user_name
                return redirect('/meowoof/index/')
            else:
                message = '亲，密码好像不对哦~'
                return render(request, 'meowoof/login.html', locals())
        else:
            return render(request, 'meowoof/login.html', locals())
    login_form = UserLoginForm()

    return render(request, 'meowoof/login.html', locals())


# 账户注册页面,已完成
def register(request):
    if request.session.get('is_login', None):
        return redirect('/meowoof/index/')

    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            user_name = register_form.cleaned_data.get('user_name')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')


            if password1 != password2:
                message = '两次输入的密码不同！'
                return render(request, 'meowoof/register.html', locals())
            else:
                same_name_user = User.objects.filter(user_name=user_name)
                if same_name_user:
                    message = '该用户名已经存在'
                    return render(request, 'meowoof/register.html', locals())

                User.objects.create(user_name=user_name, password=password1)
                return redirect('/meowoof/login/')
        else:
            return render(request, 'meowoof/register.html', locals())
    register_form = RegisterForm()
    return render(request, 'meowoof/register.html', locals())


# 退出登录，已完成
def logout(request):
    if not request.session.get('is_login', None):  # 如果本来就未登录，也就没有登出一说
        return redirect("/meowoof/login/")
    request.session.flush()
    return redirect("/meowoof/login/")


def index(request):
    if not request.session.get('is_login', None):  # 如果未登录，跳转到登录页面
        return redirect('/meowoof/login/')
    else:
        most_views_pet = Pet.objects.filter().order_by("-views")  # 按点赞数降序排列
        most_viwes_tool = Tool.objects.filter().order_by("-views")
        content = {'pet1': most_views_pet[0], 'pet2':  most_views_pet[1], 'pet3':  most_views_pet[2],
                   'tool1': most_viwes_tool[0], 'tool2': most_viwes_tool[1], 'tool3': most_viwes_tool[2]}
        return render(request, 'meowoof/index.html', content)


def pet_detail(request, pet_id):
    if not request.session.get('is_login', None):  # 如果未登录，跳转到登录页面
        return redirect('/meowoof/login/')

    pet = Pet.objects.get(id=pet_id)
    user = User.objects.get(id=request.session['user_id'])  # 从会话获取用户id


    if request.method == 'GET':  # get请求让浏览量加一
        pet.views += 1
        pet.save()




    if CollectPet.objects.filter(user=user, pet=pet):
        collect = True
    else:
        collect = False

    content = {'pet': pet, 'collect': collect}
    return render(request, 'meowoof/pet_detail.html', content)


def tool_detail(request, tool_id):
    if not request.session.get('is_login', None):  # 如果未登录，跳转到登录页面
        return redirect('/meowoof/login/')

    tool = Tool.objects.get(id=tool_id)
    user = User.objects.get(id=request.session['user_id'])  # 从会话获取用户id
    symbol = True
    if request.method == 'POST':  # post请求提交评论
        comment_content = request.POST.get('message')  # 获取前端输入内容
        if comment_content:
            Comment.objects.create(user=user, tool=tool, content=comment_content)
        else:
            symbol = False
    # 创建评论
    if request.method == 'GET':  # get请求让浏览量加一
        tool.views += 1
        tool.save()
    comments = Comment.objects.filter(tool=tool)

    current_user_like_comment_list = []  # 此列表将保存当前用户点过赞的评论的id
    for com in comments:
        current_comment = Comment.objects.filter(comment=com)
        for cc in current_comment:
            if cc.user == user:
                current_user_like_comment_list.append(com.id)



    if CollectTool.objects.filter(user=user, tool=tool):
        collect = True
    else:
        collect = False

    content = {'tool': tool, 'comments': comments, 'collect': collect, 'current_user_like_comment_list': current_user_like_comment_list, 'symbol': symbol}
    return render(request, 'meowoof/tool_detail.html', content)

def pet(request):
    if not request.session.get('is_login', None):  # 如果未登录， 跳转到登录页面
        return redirect('/meowoof/login/')
    all_pets = Pet.objects.filter().order_by("-views")
    return render(request, 'meowoof/pet.html', {'all_pets': all_pets})

def tool(request):
    if not request.session.get('is_login', None):  # 如果未登录， 跳转到登录页面
        return redirect('/meowoof/login/')
    all_tools = Tool.objects.filter().order_by("-views")
    return render(request, 'meowoof/tool.html', {'all_tools': all_tools})

def suggestion(request):
    if not request.session.get('is_login', None):  # 如果未登录， 跳转到登录页面
        return redirect('/meowoof/login/')
    all_suggestion = Suggestion.objects.filter().order_by("-views")
    return render(request, 'meowoof/suggestion.html',{'all_suggestion':all_suggestion})


def pet_search_result(request):
    if not request.session.get('is_login', None):  # 如果未登录， 跳转到登录页面
        return redirect('/meowoof/login/')

    if request.method == 'POST':
        search_text = request.POST.get('search_data')  # 从前端传入了字符串，没有使用表单
        search_text_len = len(search_text)
        if search_text_len == 0 :
            content = {'pet_search__result': []}
            return render(request, 'meowoof/pet_search_result.html', content)
        i=0
        search_result_list = [] #该列表用以储存单个字搜索的结果
        search_result_list_len = [] #该列表用以储存每个字搜索出的结果的数量
        while i<search_text_len :
            search_result_list.append(Pet.objects.filter(name__contains=search_text[i]))
            search_result_list_len.append(len(search_result_list[i]))
            i = i+1
        i=1
        search_result_list_final = [] #该列表用以进行链式搜索
        search_result_list_max = max(search_result_list_len)
        search_text_i = search_result_list_len.index(search_result_list_max)
        search_result_list_final.append(Pet.objects.filter(name__contains=search_text[search_text_i]))
        search_result_list_len[search_text_i] = 0
        #先获取单字搜索【结果数量最多】的字的下标，再对该下标对应的原字符串中的字进行filter，而后将该下标对应的搜索结果数量置0，标记为已搜索
        while i<search_text_len :
            search_result_list_max = max(search_result_list_len)
            if search_result_list_max == 0:
                break
            #该if语句为避免重复对已置0，即标记为已搜索字再次搜索
            search_text_i = search_result_list_len.index(search_result_list_max)
            if len(search_result_list_final[i - 1].filter(name__contains=search_text[search_text_i])) == 0:
                break
            #该if语句为当链式搜索中途无搜索结果时结束循环
            search_result_list_final.append(search_result_list_final[i-1].filter(name__contains=search_text[search_text_i]))
            i = i+1
        search__result = search_result_list_final[i-1] #获取链式搜索最终结果
        content = {'pet_search__result': search__result}

        return render(request, 'meowoof/pet_search_result.html', content)
    else:
        return render(request, 'meowoof/pet.html')

def tool_search_result(request):
    if not request.session.get('is_login', None):  # 如果未登录， 跳转到登录页面
        return redirect('/meowoof/login/')

    if request.method == 'POST':
        search_text = request.POST.get('search_data')  # 从前端传入了字符串，没有使用表单
        search_text_len = len(search_text)
        if search_text_len == 0 :
            content = {'tool_search__result': []}
            return render(request, 'meowoof/tool_search_result.html', content)
        i=0
        search_result_list = [] #该列表用以储存单个字搜索的结果
        search_result_list_len = [] #该列表用以储存每个字搜索出的结果的数量
        while i<search_text_len :
            search_result_list.append(Tool.objects.filter(name__contains=search_text[i]))
            search_result_list_len.append(len(search_result_list[i]))
            i = i+1
        i=1 #链式搜索第一步较特殊，需从Meal里filter，故单独写第一步
        search_result_list_final = [] #该列表用以进行链式搜索
        search_result_list_max = max(search_result_list_len)
        search_text_i = search_result_list_len.index(search_result_list_max)
        search_result_list_final.append(Tool.objects.filter(name__contains=search_text[search_text_i]))
        search_result_list_len[search_text_i] = 0
        #先获取单字搜索【结果数量最多】的字的下标，再对该下标对应的原字符串中的字进行filter，而后将该下标对应的搜索结果数量置0，标记为已搜索
        while i<search_text_len :
            search_result_list_max = max(search_result_list_len)
            if search_result_list_max == 0:
                break
            #该if语句为避免重复对已置0，即标记为已搜索字再次搜索
            search_text_i = search_result_list_len.index(search_result_list_max)
            if len(search_result_list_final[i - 1].filter(name__contains=search_text[search_text_i])) == 0:
                break
            #该if语句为当链式搜索中途无搜索结果时结束循环
            search_result_list_final.append(search_result_list_final[i-1].filter(name__contains=search_text[search_text_i]))
            i = i+1

LastPet/petweb/pet/templates/meowoof/modify_myself.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

LastPet/petweb/pet/templates/meowoof/myself.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

LastPet/petweb/pet/templates/meowoof/myself_pet_collect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

LastPet/petweb/pet/templates/meowoof/myself_tool_collect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

LastPet/petweb/pet/templates/meowoof/pet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css">
    <style>
        nav {
          background-color: #f7d6e0;
          position: fixed;
          top: -50px;
          width: 100%;
          transition: top 0.3s;

        }

        nav.visible {
          top: 0;
        }

        ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
        }

        li {
          float: left;
        }

        li a {
          display: block;
          color: darksalmon;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
            font-size: 20px;
        }

        .logout {
          float: right;
        }
    </style>
</head>
<body background="../../static/image/pet.jpg"
      style="background-repeat:no-repeat;
               background-attachment:fixed;
               background-size:100% 100%; ">
    <nav id="navbar">
        <div style="background-color: #333333;
                height: 2px"></div>
    <ul>
      <li><a href="{% url 'meowoof:pet' %}">宠物</a></li>
      <li><a href="{% url 'meowoof:tool' %}">宠物用品</a></li>
      <li><a href="{% url 'meowoof:suggestion' %}">宠物建议</a></li>
      <li class="logout"><a href="{% url 'meowoof:logout' %}">登出</a></li>
    </ul>
        <div style="background-color: #333333;
                height: 5px"></div>
  </nav>
    <!--这里搜索不适用表单，使用传进去字符串-->
    <center>
        <form  class="search-form" method="post" action="{% url "meowoof:pet_search_result" %}">
        {% csrf_token %}
        <input class="search-form-input" type="text" name="search_data" placeholder="请输入关键字" >

        <input class="search-form-button" type="submit" value="查询" >
    </form>
    </center>


    <section class="pet-gallery">
        {% for c in all_pets %}
           <a href="../pet_detail/{{ c.id }}/">
            <div class="pet">
                <img href="../pet_detail/{{ c.id }}/" width="360" height="270" src="{{ c.picture.url }}" alt="图片丢惹" />

                <div class="pet-info">
                    <h2>{{c.name}}</h2>
                    <p>{{c.character}}</p>
                </div>
            </div>
           </a>

    {% endfor %}
    </section>


</body>
<script>
    var navbar = document.getElementById('navbar');
    var prevScrollpos = window.pageYOffset;

    window.onscroll = function() {
      var currentScrollPos = window.pageYOffset;
      if (prevScrollpos > currentScrollPos) {
        navbar.classList.add('visible');
      } else {
        navbar.classList.remove('visible');
      }
      prevScrollpos = currentScrollPos;
    };

</script>
</html>

LastPet/petweb/pet/templates/meowoof/pet_search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css">
    <style>
        nav {
          background-color: #f7d6e0;
          position: fixed;
          top: -50px;
          width: 100%;
          transition: top 0.3s;

        }



        ul {
          list-style-type: none;
          margin: 0;
          padding: 0;

        }

        li {
          float: left;
            margin-top: 20px;
        }

        li a {
          display: block;
          color: darksalmon;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
            font-size: 20px;
        }

        .logout {
          float: right;
        }
    </style>
</head>
<body background="../../static/image/pet.jpg"
      style="background-repeat:no-repeat;
               background-attachment:fixed;
               background-size:100% 100%; ">
    <nav>
        <div style="background-color: #333333;
                height: 2px"></div>

    <ul>
      <li><a href="{% url 'meowoof:pet' %}">宠物</a></li>
      <li><a href="{% url 'meowoof:tool' %}">宠物用品</a></li>
      <li><a href="{% url 'meowoof:suggestion' %}">宠物建议</a></li>
      <li class="logout"><a href="{% url 'meowoof:logout' %}">登出</a></li>
        <center>
            <h3> 宠物详情</h3>
        </center>
    </ul>

  </nav>
    <!--这里搜索不适用表单，使用传进去字符串-->
    <center>
        <form  class="search-form" method="post" action="{% url "meowoof:pet_search_result" %}">
        {% csrf_token %}
        <input class="search-form-input" type="text" name="search_data" placeholder="请输入关键字" >

        <input class="search-form-button" type="submit" value="查询" >
    </form>
    </center>


    <section class="pet-gallery">
        {% for c in pet_search__result %}
           <a href="../pet_detail/{{ c.id }}/">
            <div class="pet">
                <img href="../pet_detail/{{ c.id }}/" width="360" height="270" src="{{ c.picture.url }}" alt="图片丢惹" />

                <div class="pet-info">
                    <h2>{{c.name}}</h2>
                    <p>{{c.character}}</p>
                </div>
            </div>
           </a>

    {% endfor %}
    </section>


</body>
<script>
    var navbar = document.getElementById('navbar');
    var prevScrollpos = window.pageYOffset;

    window.onscroll = function() {
      var currentScrollPos = window.pageYOffset;
      if (prevScrollpos > currentScrollPos) {
        navbar.classList.add('visible');
      } else {
        navbar.classList.remove('visible');
      }
      prevScrollpos = currentScrollPos;
    };

</script>
</html>

LastPet/petweb/pet/templates/meowoof/tool.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css">
    <style>
        nav {
          background-color: #f7d6e0;
          position: fixed;
          top: -50px;
          width: 100%;
          transition: top 0.3s;

        }

        nav.visible {
          top: 0;
        }

        ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
        }

        li {
          float: left;
        }

        li a {
          display: block;
          color: darksalmon;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
            font-size: 20px;
        }

        .logout {
          float: right;
        }
    </style>
</head>
<body background="../../static/image/pet.jpg"
      style="background-repeat:no-repeat;
               background-attachment:fixed;
               background-size:100% 100%; ">
    <nav id="navbar">
        <div style="background-color: #333333;
                height: 2px"></div>
    <ul>
      <li><a href="{% url 'meowoof:pet' %}">宠物</a></li>
      <li><a href="{% url 'meowoof:tool' %}">宠物用品</a></li>
      <li><a href="{% url 'meowoof:suggestion' %}">宠物建议</a></li>
      <li class="logout"><a href="{% url 'meowoof:logout' %}">登出</a></li>
    </ul>
        <div style="background-color: #333333;
                height: 5px"></div>
  </nav>
    <!--这里搜索不适用表单，使用传进去字符串-->
    <center>
        <form  class="search-form" method="post" action="{% url "meowoof:tool_search_result" %}">
        {% csrf_token %}
        <input class="search-form-input" type="text" name="search_data" placeholder="请输入关键字" >

        <input class="search-form-button" type="submit" value="查询" >
    </form>
    </center>


    <section class="pet-gallery">
        {% for c in all_tools %}
           <a href="../tool_detail/{{ c.id }}/">
            <div class="pet">
                <img href="../tool_detail/{{ c.id }}/" width="360" height="270" src="{{ c.picture.url }}" alt="图片丢惹" />

                <div class="pet-info">
                    <h2>{{c.name}}</h2>
                    <p>{{c.character}}</p>
                </div>
            </div>
           </a>

    {% endfor %}
    </section>


</body>
<script>
    var navbar = document.getElementById('navbar');
    var prevScrollpos = window.pageYOffset;

    window.onscroll = function() {
      var currentScrollPos = window.pageYOffset;
      if (prevScrollpos > currentScrollPos) {
        navbar.classList.add('visible');
      } else {
        navbar.classList.remove('visible');
      }
      prevScrollpos = currentScrollPos;
    };

</script>
</html>